version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    depends_on:
      - "mysql"
    restart: always
    ports:
      - '4466:4466'
    networks:
      - back-tier
      - db-tier
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    networks:
      - db-tier
    volumes:
      - mysql:/var/lib/mysql
  back-end:
    restart: always
    container_name: "back-end"
    build: .
    depends_on:
      - "prisma"
    ports:
      - "4000:4000"
    networks:
      - back-tier
volumes:
  mysql: ~
networks:
  back-tier:
    driver: bridge
  db-tier:
    driver: bridge
