name: Build, Test

on: [push, pull_request]

jobs:
  build:
    name: Build server
    runs-on: ubuntu-latest

    strategy:
      matrix:
          node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get dependencies
      run: npm i 
      working-directory: ./server
    - name: Run Tests
      run: npm run build
      working-directory: ./server
