name: Build, Test

on: [push, pull_request]

jobs:
  build:
    name: Build server
    runs-on: ubuntu-latest

    steps:
    - name: Set Node.js 8.x
      uses: actions/setup-node@master
      with:
        version: 10.x
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Get dependencies
      run: npm i 
      working-directory: ./server
    - name: Run Tests
      run: npm run build
      working-directory: ./server
